controllers/UserController.php
<?php
/**
 * Last modified: 18.12.11 01:19:19
 * Hash: a31022880624333a9ee669d21af8a9ed013bb744
 */

namespace app\controllers;

use app\controllers\base\RestController;
use app\models\Email;
use app\models\form\Login;
use app\models\form\PasswordReset;
use app\models\form\RequestPasswordReset;
use app\models\Log;
use app\models\Token;
use app\models\Transfer;
use app\models\User;
use Yii;
use yii\db\Query;
use yii\filters\AccessControl;
use yii\filters\HttpCache;
use yii\helpers\Url;
use yii\web\BadRequestHttpException;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\web\Response;
use yii\web\ServerErrorHttpException;

class UserController extends RestController
{
    public function behaviors(): array
    {
        return [
            'cache' => [
                'class' => HttpCache::class,
                'enabled' => !YII_DEBUG,
                'only' => ['login', 'signup', 'request'],
                'lastModified' => function () {
                    $time = time();
                    return $time - $time % 3600;
                }
            ],
            'access' => [
                'class' => AccessControl::class,
                'only' => ['logout', 'request', 'reset', 'profile'],
                'rules' => [
                    'guest' => [
                        'allow' => true,
                        'actions' => ['request', 'reset'],
                        'roles' => ['?']
                    ],
                    'member' => [
                        'allow' => true,
                        'actions' => ['profile', 'logout'],
                        'roles' => ['@']
                    ]
                ]
            ]
        ];
    }

    /**
     * @param $action
     * @return bool
     * @throws \yii\web\BadRequestHttpException
     */
    public function beforeAction($action)
    {
        if ('authorize' === $action->id || 'login' === $action->id) {
            Yii::$app->request->enableCsrfValidation = false;
        }
        return parent::beforeAction($action);
    }

    protected function saveSponsor($nick): string
    {
        $nick = $nick ?: Yii::$app->request->getCookie(User::SPONSOR_COOKIE, User::ROOT_NICK);
        if (User::ROOT_NICK !== $nick) {
            setcookie(User::SPONSOR_COOKIE, $nick, time() + User::SPONSOR_COOKIE_EXPIRES, '/');
        }
        return $nick;
    }

    public function actionSignup($sponsor = null)
    {
        if (!Yii::$app->user->getIsGuest()) {
            return $this->redirect(['user/profile', 'nick' => Yii::$app->user->identity->nick]);
        }

        $this->layout = 'outdoor';
        $sponsor = $this->saveSponsor($sponsor);
        $model = new User(['scenario' => User::SCENARIO_REGISTER]);
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $model->parent = User::getIdByNick($model->sponsor ?: $sponsor ?: User::ROOT_NICK);
            $model->generateSecret();
            $model->save(false);
            if (Yii::$app->user->login($model)) {
//                Email::send($model->email,
//                    Yii::t('app', '{name}: Welcome', ['name' => Yii::$app->name]),
//                    Yii::t('app', "Dear, {nick}\nThank you for registration at {name}", [
//                        'nick' => $model->nick,
//                        'name' => Yii::$app->name
//                    ]));
                Log::log('user', 'signup', ['ip' => $model->ip]);
                return $this->redirect(['user/profile', 'nick' => $model->nick]);
            }
        } else {
            $model->sponsor = $sponsor;
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    public function actionLogin($sponsor = null)
    {
        if (!Yii::$app->user->getIsGuest()) {
            return $this->redirect(['user/profile', 'nick' => Yii::$app->user->identity->nick]);
        }

        $this->layout = 'outdoor';
        $this->saveSponsor($sponsor);
        $model = new Login();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $data = ['ip' => $model->ip];
            $user = null;
            if (Login::checkLoginAttempt(['ip' => Yii::$app->request->getUserIP()])) {
                $user = $model->getUser();
                if ($user) {
                    if (Login::checkLoginAttempt(['user' => $user->id])) {
                        if ($user->validatePassword($model->password)) {
                            Yii::$app->user->login($user);
                            Log::log('auth', 'login', $data);
                            $url = Yii::$app->user->getReturnUrl();
                            return $this->redirect(empty($url) ? ['user/profile', 'nick' => $user->nick] : $url);
                        }
                        $model->addError('password', Yii::t('app', 'Invalid password'));
                    }
                } else {
                    $model->addError('login', Yii::t('app', 'User does not exists'));
                }
            }
            if (!$user) {
                $data['login'] = $model->login;
            }
            Log::log('auth', 'invalid', $data, $user ? $user->id : null);
        }

        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * @param $name
     * @param $value
     * @return array
     * @throws BadRequestHttpException
     */
    public function actionExists($name, $value) {
        Yii::$app->response->format = Response::FORMAT_JSON;
        if ('nick' === $name || 'email' === $name) {
            return ['result' => User::find()->where([$name => $value])->limit(1)->count() > 0];
        }
        throw new BadRequestHttpException('Invalid name ' . $name);
    }

    public function actionLogout()
    {
        $id = $this->getUser()->id;
        Yii::$app->user->logout(false);
        Log::log('auth', 'logout', null, $id);
        return $this->redirect(['user/login']);
    }

    /**
     * @param $nick
     * @return array|string
     * @throws \yii\web\NotFoundHttpException
     * @throws \yii\db\Exception
     */
    public function actionProfile($nick)
    {
        $informer = (new Query())
            ->from('informer')
            ->where(['nick' => $nick])
            ->one();
        if (empty($informer)) {
            throw new NotFoundHttpException(Yii::t('app', 'User not found'));
        }
        $informer = array_merge($informer, Transfer::getFinance($informer['id']));

        if ($informer['parent']) {
            $informer['parent'] = json_decode($informer['parent']);
        }

        return $this->render('profile', [
            'model' => $informer,
            'programs' => $this->getUser()->getProgramNodes()
        ]);
    }

    /**
     * @return array|string
     * @throws \yii\base\Exception
     */
    public function actionRequest()
    {
        $this->layout = 'outdoor';
        $model = new RequestPasswordReset();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $user = $model->getUser();
            $success = $user && ($code = $user->generateCode())
                && Email::send($user->email, Yii::t('app', 'Password Recovery in the "{name}" project', [
                    'name' => Yii::$app->name
                ]),
                    Yii::t('app', "Hello!\nYou requested a password reset from your account.\nFollow the link to reset your password - {url} \n\nSincerely, \"{name}\" Administration", [
                        'url' => Url::to(['user/reset', 'code' => $code], true),
                        'name' => Yii::$app->name
                    ]));
            if ($success) {
                Yii::$app->session->addFlash('success', Yii::t('app', 'Check your email'));
            } else {
                Yii::$app->session->addFlash('error', Yii::t('app', 'User not found'));
            }
        }
        return $this->render('request', ['model' => $model]);
    }

    /**
     * @param $code
     * @return array|string|Response
     * @throws \yii\base\InvalidArgumentException
     * @throws ServerErrorHttpException
     * @throws \Exception
     * @throws \Throwable
     * @throws \yii\db\StaleObjectException
     */
    public function actionReset($code)
    {
        $this->layout = 'outdoor';
        $model = new PasswordReset();
        $token = Token::findOne(['id' => $code]);
        if ($token) {
            if ($model->load(Yii::$app->request->post()) && $model->validate()) {
                $user = User::findOne(['id' => $token->user]);
                if (!$user) {
                    throw new ServerErrorHttpException('User not found');
                }
                /** @var User $user */
                $user->password = $model->password;
                $user->generateSecret();
                if ($user->save(false) && $token->delete()) {
                    Yii::$app->session->addFlash('success', Yii::t('app', 'Password changed'));
                }
                return $this->redirect(['user/login']);
            }
        } else {
            Yii::$app->session->addFlash('error', Yii::t('app', 'Password recovery code not found'));
//            return $this->redirect(['user/login']);
        }
        return $this->render('reset', [
            'token' => $token,
            'model' => $model
        ]);
    }

    /**
     * @param $nick
     * @param $token
     * @return Response
     * @throws ForbiddenHttpException
     * @throws ServerErrorHttpException
     */
    public function actionAuthorize($nick, $token): Response
    {
        /** @var Token $auth */
        $auth = Token::findOne(['id' => $token]);
        if ($auth) {
            $user = User::findOne(['nick' => $nick]);
            if ($user) {
                $u = $auth->userObject;
                if (!$u) {
                    throw new ServerErrorHttpException('User not found');
                }

views/user/login.php
<?php
/**
 * Last modified: 18.09.22 16:02:09
 * Hash: 1fa5c210035bb80c12ca903a71b8ac61bfcf1acf
 */

use app\models\User;
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\form\Login */
/* @var $form ActiveForm */

$this->title = Yii::t('app', 'Sign in');
?>

<div class="user login">
    <?php $form = ActiveForm::begin(); ?>
    <div class="fields">
        <?= $form->field($model, 'login')
            ->textInput(['maxlength' => User::LENGTH_EMAIL, 'placeholder' => Yii::t('app', 'Your Login')])
            ->label(false) ?>
        <?= $form->field($model, 'password')
            ->passwordInput(['maxlength' => User::LENGTH_PASSWORD, 'placeholder' => Yii::t('app', 'Your Password')])
            ->label(false) ?>
    </div>

    <div class="control">
        <?= Html::submitButton(Yii::t('app', 'Sign in')) ?>
        <?= Html::a(Yii::t('app', 'Signup'), ['user/signup']) ?>
        <?= Html::a(Yii::t('app', 'Forgot Password?'), ['user/request']) ?>
    </div>

    <?php ActiveForm::end(); ?>
</div>

views/user/profile.php
<?php
/**
 * Last modified: 18.11.20 23:53:29
 * Hash: c56312e58525503fa79105526a40f49938593f0c
 */

use app\helpers\Html;
use app\models\Transfer;

/* @var $program array */
/* @var $this \yii\web\View */
/* @var $model array */
/* @var $programs array */

$parent = $model['parent'];
$isMe = Yii::$app->user->getIsGuest() ? false : Yii::$app->user->identity->nick === $model['nick'];
?>
<div class="user profile">
    <div class="row">
        <ul class="informer clean">
            <li class="col-lg-3">
                <div class="icon purpure"></div>
                <div>
                    <span class="value money usd"><?=
                        $model['accrue'][Transfer::CURRENCY] +
                        (empty($model['refund']) ? 0 : $model['refund'][Transfer::CURRENCY])
                        ?></span>
                    <span class="name"><?= Yii::t('app', 'Money from the matrices') ?></span>
                </div>
            </li>
            <li class="col-lg-3">
                <div class="icon blue"></div>
                <div>
                    <span class="value money usd"><?= $model['bonus'][Transfer::CURRENCY] ?></span>
                    <span class="name"><?= Yii::t('app', 'Linear income') ?></span>
                </div>
            </li>
            <li class="col-lg-3">
                <div class="icon pink"></div>
                <div>
                    <span class="value"><?= $model['visit'] ?></span>
                    <span class="name"><?= Yii::t('app', 'Referral link transitions') ?></span>
                </div>
            </li>
            <li class="col-lg-3">
                <div class="icon green"></div>
                <div>
                    <span class="value"><?= $model['referral'] ?></span>
                    <span class="name"><?= Yii::t('app', 'The team') ?></span>
                </div>
            </li>
        </ul>
    </div>
    <div class="row program-list">
        <?php if ($parent): ?>
            <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                <div class="widget cart-sponsor">
                    <h3 class="widget-title"><?= Yii::t('app', 'My sponsor') ?></h3>
                    <div class="widget-content">
                        <?= !empty($parent->forename) && !empty($parent->surname)
                            ? Html::tag('p', $parent->forename . ' ' . $parent->surname, ['class' => 'name'])
                            : Yii::t('app', 'Sponsor did not give name and surname') ?>
                        <ul>
                            <li>
                                <i class="material-icons">supervised_user_circle</i>
                                <span><strong>Login:</strong> <?= $parent->nick ?></span>
                            </li>
                            <?php
                            if (!empty($parent->skype)) : ?>
                                <li>
                                    <i class="material-icons">perm_phone_msg</i>
                                    <span><strong>Skype:</strong> <?= $parent->skype ?></span>
                                </li>
                            <?php else :
                                echo Yii::t('app', 'Sponsor does not have Skype');
                            endif; ?>

                        </ul>
                    </div>
                </div>
            </div>
        <?php endif ?>
        <?= Yii::$app->view->render('@app/views/program/_list', [
            'programs' => $programs
        ]) ?>
    </div>
</div>

views/user/request.php
<?php

use app\models\User;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/**
 * @var $this yii\web\View
 * @var $message string
 * @var $model app\models\form\RequestPasswordReset
 * @var $form ActiveForm
 */

$this->title = Yii::t('app', 'Password Recovery');
?>

<div class="user request">
    <?php $form = ActiveForm::begin(); ?>
    <h4><?= Yii::t('app', 'Password Recovery Request') ?></h4>

    <div class="fields">
        <?= $form->field($model, 'login')->textInput(['maxlength' => User::LENGTH_EMAIL]) ?>
    </div>

    <div class="control">
        <?= Html::submitButton(Yii::t('app', 'Send Email')) ?>
        <?= Html::a(Yii::t('app', 'Signup'), ['user/signup']) ?>
        <?= Html::a(Yii::t('app', 'Sign in'), ['user/login']) ?>
    </div>
    <?php ActiveForm::end(); ?>
</div>

views/user/reset.php
<?php
/**
 * Last modified: 18.10.06 16:16:46
 * Hash: b7a5f6530c066315ee2823271de15bb6ebf26d12
 *
 * @var $this yii\web\View
 * @var $message string
 * @var $model app\models\form\RequestPasswordReset
 * @var $form ActiveForm
 * @var $token \app\models\Token
 */

use app\models\User;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

$this->title = Yii::t('app', 'Password Recovery');

if ($token): ?>
    <div class="user reset">
        <?php $form = ActiveForm::begin(); ?>

        <div class="fields">
            <?= $form->field($model, 'password')->passwordInput(['maxlength' => User::LENGTH_PASSWORD]) ?>
            <?= $form->field($model, 'repeat')->passwordInput(['maxlength' => User::LENGTH_PASSWORD]) ?>
        </div>

        <div class="control">
            <?= Html::submitButton(Yii::t('app', 'Save')) ?>
            <?= Html::a(Yii::t('app', 'Cancel'), ['user/login']) ?>
        </div>
        <?php ActiveForm::end() ?>
    </div>
<?php else: ?>
    <div class="user reset">
        <?php $form = ActiveForm::begin(); ?>
        <div class="control">
            <?= Html::a(Yii::t('app', 'Signup'), ['user/signup']) ?>
            <?= Html::a(Yii::t('app', 'Sign in'), ['user/login']) ?>
        </div>
        <?php ActiveForm::end() ?>
    </div>
<?php endif;

views/user/signup.php
<?php
/**
 * Last modified: 18.12.01 15:22:01
 * Hash: 2fa9440463ea5af6c5f21b23e2f08aedf6bd62c0
 */

use app\models\User;
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\User */
/* @var $form yii\widgets\ActiveForm */

$this->title = Yii::t('app', 'Signup');
?>

<div class="user signup">
    <?php if (Yii::$app->params['signup']): ?>
        <?php $form = ActiveForm::begin(['enableAjaxValidation' => true]); ?>
        <h4><?= Yii::t('app', 'Create an account') ?></h4>

        <div class="fields">
            <?= $form->field($model, 'nick')->textInput(['maxlength' => User::LENGTH_NICK]) ?>
            <?= $form->field($model, 'email')->textInput(['maxlength' => User::LENGTH_EMAIL]) ?>
            <?= $form->field($model, 'password')->passwordInput(['maxlength' => User::LENGTH_PASSWORD]) ?>
            <?= $form->field($model, 'repeat')->passwordInput(['maxlength' => User::LENGTH_PASSWORD]) ?>
            <?= $form->field($model, 'pin')->passwordInput([
                'maxlength' => User::LENGTH_PIN,
                'placeholder' => Yii::t('app', 'Save and do not pass it to anyone!')
            ]) ?>
            <?= $form->field($model, 'telegram')->textInput(['maxlength' => User::LENGTH_TELEGRAM]) ?>
            <?= $form->field($model, 'skype')->textInput(['maxlength' => User::LENGTH_SKYPE]) ?>
            <?= $form->field($model, 'sponsor')->textInput(['maxlength' => User::LENGTH_NICK]) ?>
            <div class="agreement">
                <?= $form->field($model, 'agree')->checkbox() ?>
                <?= Yii::t('app', '<a href="/agreement" target="_blank">Terms and Conditions</a>') ?>
            </div>
        </div>

        <div class="control">
            <?= Html::submitButton(Yii::t('app', 'Signup')) ?>
            <?= Html::a(Yii::t('app', 'Sign in'), ['user/login']) ?>
            <?= Html::a(Yii::t('app', 'Forgot Password?'), ['user/request']) ?>
        </div>
        <?php ActiveForm::end(); ?>
    <?php else: ?>
        <div><?= Yii::t('app', 'Signup is closed') ?></div>
    <?php endif ?>
</div>