controllers/NodeController.php
<?php
/**
 * Last modified: 18.09.25 03:46:23
 * Hash: b5146d49a8bb49978592b2badcb15f988c55295e
 */

namespace app\controllers;


use app\controllers\base\RestController;
use app\helpers\SQL;
use app\models\Log;
use app\models\Node;
use app\models\Offer;
use app\models\Program;
use app\models\Swap;
use app\models\User;
use Yii;
use yii\filters\AccessControl;
use yii\filters\auth\CompositeAuth;
use yii\filters\auth\QueryParamAuth;
use yii\web\ForbiddenHttpException;
use yii\web\HttpException;
use yii\web\NotFoundHttpException;
use yii\web\Response;
use yii\web\ServerErrorHttpException;

class NodeController extends RestController
{
    public function behaviors(): array
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@']
                    ]
                ]
            ],
            'authenticator' => [
                'class' => CompositeAuth::class,
                'only' => ['view'],
                'authMethods' => [
                    QueryParamAuth::class,

                ]
            ]
        ];
    }

    /**
     * @param int $id
     * @param int|null $offer
     * @return array|string|Response
     * @throws NotFoundHttpException
     * @throws \yii\db\Exception
     * @throws ForbiddenHttpException
     */
    public function actionView(int $id, int $offer = null)
    {
        $this->layout = 'embed';
        return $this->actionMatrix($id, $offer);
    }

    /**
     * @param int $id
     * @param int $offer
     * @param bool $direct
     * @return array|string|Response
     * @throws NotFoundHttpException
     * @throws \yii\db\Exception
     * @throws ForbiddenHttpException
     */
    public function actionMatrix(int $id, ?int $offer = null, bool $direct = false)
    {
        Offer::checkAvailability($offer);
        $ref_node = Node::findOne($id);
        if (!$ref_node) {
            throw new NotFoundHttpException('Node not found');
        }
        $root = $ref_node->getRoot();
        if ($direct) {
            $this->layout = 'embed';
        } else {
            if ($root->id !== $id) {
                return $this->redirect(['node/matrix',
                    'id' => $root->id,
                    'offer' => $offer
                ]);
            }
        }
        $models = Node::getMatrix($id);
        $nodes = [];
        $level = 0;
        foreach ($models as $model) {
            $level = max($level, $model['level']);
            $nodes[$model['number']] = $model;
        }
        $program = null;
        if (\count($models) > 0) {
            $program = Program::findOne($root['program']);
        } else {
            throw new NotFoundHttpException('Matrix not found');
        }
        return $this->render('matrix', [
            'offer' => $offer,
            'buy' => $offer !== null && $offer !== 0,
            'program' => $program,
            'nodes' => $nodes,
            'root' => $root
        ]);
    }

    /**
     * @param $program
     * @param int $offer
     * @return Response
     * @throws \yii\db\Exception
     * @throws ForbiddenHttpException
     */
    public function actionRandom(int $program, ?int $offer = null)
    {
        Offer::checkAvailability($offer);
        $id = SQL::scalar('select id from matrix_count
          where opened and not closed and "program" = :program
          order by filled, random() limit 1', [
            ':program' => $program
        ]);
        if (null === $id) {
            $id = SQL::scalar('select id from matrix_count
              where not closed and "program" = :program
              order by filled, random() limit 1', [
                ':program' => $program
            ]);
            Log::debug('matrix', 'not_found', ['found' => $id]);
        }
        return $this->redirect(['matrix', 'id' => $id, 'offer' => $offer]);
    }

    /**
     * @param $id
     * @param $number
     * @param $offer
     * @return Response
     * @throws HttpException
     * @throws \Error
     * @throws \Exception
     * @throws \Throwable
     * @throws \yii\db\Exception
     * @throws \yii\db\StaleObjectException
     */
    public function actionBuy(int $id, int $number, ?int $offer = null): ?Response
    {
        /** @var User $user */
        $user = Yii::$app->user->identity;
        $tx = Yii::$app->db->beginTransaction();
        try {
//            $node_id = 0;
            if ($offer > 0) {
                /**
                 * @var Offer $o
                 */
                $o = Offer::findOne($offer);
                if ($o) {
                    if ($user->id === $o->user && !$o->used) {
//                        header('OPEN: ' . $id);
                        $node_id = $o->open($id, $number);
                    } else {
                        throw new ForbiddenHttpException('It is not your offer');
                    }
                } else {
                    throw new NotFoundHttpException('Offer not found');
                }
            } else {
//                header('BUY: ' . $id);
                $node_id = Program::buy($id, $user->id, $number);
            }
            if ($node_id > 0) {
                $tx->commit();
                return $this->redirect(['node/matrix', 'id' => $node_id]);
            }

            throw new ServerErrorHttpException('Invalid node_id: ' . $node_id);
        } catch (HttpException $ex) {
            if (402 === $ex->statusCode) {
                return $this->redirect(['transfer/pay']);
            }

            throw $ex;
        }
    }

    /**
     * @param int $id
     * @return array
     * @throws NotFoundHttpException
     * @throws \yii\db\Exception
     */
    public function actionRoot(int $id): array
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        $node = Node::findOne($id);
        if ($node) {
            return [
                'count' => $node->getMemberCount(),
                'result' => $node->attributes
            ];
        }
        throw new NotFoundHttpException();
    }
}

controllers/ProgramController.php
<?php
/**
 * Last modified: 18.11.16 04:03:18
 * Hash: c934debf160f1d56ec2126c4793387811a85d184
 */

namespace app\controllers;


use app\behaviors\Access;
use app\controllers\base\RestController;
use app\helpers\Utils;
use app\models\form\Username;
use app\models\Node;
use app\models\Offer;
use app\models\Program;
use app\models\User;
use Yii;
use yii\filters\AccessControl;
use yii\web\BadRequestHttpException;
use yii\web\NotFoundHttpException;
use yii\web\Response;

class ProgramController extends RestController
{
    public function behaviors(): array
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only' => ['index', 'open', 'sponsor'],
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['index', 'open', 'sponsor'],
                        'roles' => ['@']
                    ]
                ]
            ]
        ];
    }

    /**
     * @return array|string
     * @throws \yii\base\InvalidArgumentException
     * @throws \yii\db\Exception
     */
    public function actionIndex()
    {
        return $this->render('index', [
            'models' => $this->getUser()->getProgramNodes()
        ]);
    }

    /**
     * @param int $program
     * @param User|null $user
     * @param int|null $offer
     * @return Response
     * @throws \yii\db\Exception
     */
    protected function openNode(int $program, ?User $user, ?int $offer = null): Response
    {
        if ($node = Program::tryOpen($program, $user)) {
            return $this->redirect(['node/matrix',
                'nick' => $this->getUser()->nick,
                'id' => $node->id,
                'offer' => $offer
            ]);
        }
        return $this->redirect(['program/sponsor',
            'id' => $program,
            'offer' => $offer
        ]);
    }

    /**
     * @param int $id
     * @param int $offer
     * @param int $level
     * @return Response
     * @throws NotFoundHttpException
     * @throws \yii\db\Exception
     * @throws \yii\web\ForbiddenHttpException
     * @throws BadRequestHttpException
     */
    public function actionOpen(int $id, int $offer = -1, int $level = 1): Response
    {
        if (!(1 === $level || 2 === $level)) {
            throw new BadRequestHttpException('Invalid level in program.open');
        }
        Offer::checkAvailability($offer);
        if ($offer > 0 || Program::canBuy($id)) {
            $parent = $this->getUser();
            for ($i = 0; $i < $level; $i++) {
                if (!($parent = $parent->parentObject)) {
                    throw new NotFoundHttpException('Parent user not found in program.open');
                }
            }
            return $this->openNode($id, $parent, $offer);
        }
        return $this->redirect(['invoice/payment', 'nick' => Yii::$app->user->identity->nick]);
    }

    /**
     * @param int $id
     * @param int $offer
     * @return array|string|Response
     * @throws NotFoundHttpException
     * @throws \yii\db\Exception
     * @throws \yii\web\ForbiddenHttpException
     */
    public function actionSponsor(int $id, int $offer = -1)
    {
        Offer::checkAvailability($offer);
        /** @var Node $node */
        $node = Node::findOne($id);
        if (!$node) {
            throw new NotFoundHttpException("Matrix #$id not found (choose-sponsor)");
        }
        $program = $node->programObject;
        $model = new Username();
        /** @var Node $sponsor_node */
        $sponsor_node = Node::find()
            ->where(['user' => Yii::$app->user->identity->parent, 'program' => $node->program])
            ->one();
        if ($sponsor_node && !$sponsor_node->isMatrixActive()) {
            /** @var Node $sponsor_next_node */
            $sponsor_next_node = Node::find()
                ->where(['user' => Yii::$app->user->identity->parent, 'program' => $node->program + 1])
                ->one();
            if ($sponsor_next_node) {
                Yii::$app->session->addFlash('warning', Yii::t('app', 'Your sponsor has moved to the matrix {name}', [
                    'name' => $sponsor_next_node->programObject->name
                ]));
            } else {
                Yii::$app->session->addFlash('warning', Yii::t('app', 'Your sponsor has closed the matrix {name}', [
                    'name' => $program->name
                ]));
            }
        }
//        else {
//            Yii::$app->session->addFlash('warning', Yii::t('app', 'You have no sponsor in {name}', [
//                'name' => $program->name
//            ]));
//        }
        if ($model->load(Yii::$app->request->post()) && $model->validate(['nick'])) {
            /** @var User $found */
            $found = User::find()
                ->where(['nick' => $model->nick])
                ->select(['id'])
                ->one();
            if ($found) {
                /** @var Node $target_node */
                $target_node = Node::find()
                    ->where(['user' => $found->id, 'program' => $node->program])
                    ->one();
                if ($target_node) {
                    return $this->openNode($id, $found, $offer);
                }
                $model->addError('nick', Yii::t('app', 'This user is not in the matrix {name}', [
                    'name' => $program->name
                ]));
            } else {
                $model->addError('nick', Yii::t('app', 'Not found'));
            }
        }
        return $this->render('sponsor', [
            'id' => $id,
            'offer' => $offer,
            'model' => $model,
            'program' => $program
        ]);
    }
}

views/program/_list.php
<?php
/**
 * Last modified: 18.11.20 23:49:27
 * Hash: 23b0d8f396c41e939bef2d3b008c84d636d6c8ac
 *
 * @var $this \yii\web\View
 * @var $programs array
 */

use app\helpers\Html;

$user = Yii::$app->user->identity;

foreach ($programs as $program) {
    $name = str_replace(array(' Stream', ' Lagoon'), '', $program['name']);
    $lower = strtolower($name);
    ?>
    <div class="col-md-4 col-lg-4 col-sm-12 col-xs-12">
        <div class="program <?= $lower ?>">
            <div class="image">
                <?= Html::img("/img/$lower.png", ['alt' => "Matrix $name"]) ?>
            </div>
            <div class="program-inform">
                <h3 class="name"><?= $name ?></h3>
                <div>
                    <span class="price money usd"><?= $program['price'] ?></span>
                </div>
                <div class="control">
                    <?php
                    if ($program['node'] > 0) {
                        echo Html::a(
                            Yii::t('app', 'Info-products'),
                            ['course/index', 'program_id' => 0 === $program['id'] % 2 ? $program['id'] - 1 : $program['id']],
                            ['class' => 'courses']
                        );
                        if (false === $program['active']) {
                            echo Html::tag('div', Yii::t('app', 'Matrix is full'), [
                                'class' => 'full'
                            ]);
                        } else {
                            echo Html::a(Yii::t('app', 'View'), ['node/matrix',
                                'nick' => $user->nick,
                                'id' => $program['node']
                            ]);
                        }
                    } else {
                        echo Html::a(Yii::t('app', 'Open'), [
                            'program/open',
                            'nick' => $user->nick,
                            'id' => $program['id']
                        ], [
                                'target' => '_blank'
                        ]);
                    }
                    ?>
                </div>
            </div>
        </div>
    </div>
    <?php
}

views/program/index.php
<?php
/**
 * Last modified: 18.07.26 20:47:43
 * Hash: 06a701a7ce9777e4dd45d32865e6bf96fa81d24a
 */

/* @var $models array */
/* @var $this \yii\web\View */

?>
<div class="row">
    <div class="programs index program-list">
		<?= Yii::$app->view->render('_list', ['programs' => $models]) ?>
    </div>
</div>

views/program/sponsor.php
<?php
/**
 * Last modified: 18.10.06 15:30:47
 * Hash: 0182c8e99c218d68d92a8dd798bb097bad742758
 */
/* @var $offer int|null */
/* @var $this \yii\web\View */
/* @var $model \app\models\form\Username */
/** @var \app\models\Program $program */

/* @var $id int */

use app\helpers\Html;
use yii\widgets\ActiveForm;

?>
<article class="program sponsor">
    <p>
        <?= Yii::t('app', 'Enter the login of the member of the matrix you want to stand in or click the "Random Matrix" button', [
            'name' => $program->name
        ]) ?>
    </p>
    <?php $form = ActiveForm::begin() ?>
    <?= $form->field($model, 'nick')
        ->label(false /* Yii::t('app', 'Choose sponsor') */) ?>
    <?= Html::submitButton(Yii::t('app', 'Open')) ?>

    <?= Html::a(Yii::t('app', 'Random matrix'), ['node/random',
        'nick' => Yii::$app->user->identity->nick,
        'program' => $id,
        'buy' => !($offer > 0),
        'offer' => $offer
    ], [
        'class' => 'button'
    ]) ?>
    <?php ActiveForm::end() ?>
</article>